config/routes.rb
Rails.application.routes.draw do
  resources :artists
  devise_for :users
  resources :pictures
  resource :cart, only: [:show]
  resources :order_item, only: [:create, :update, :destroy]
  resources :charges
  
  root to: "pictures#index"

  get '/about' =>'welcome#about'

  get '/contact' => 'welcome#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/picture.rb
class Picture < ActiveRecord::Base

    has_many :order_items

     default_scope { where(active: true) }

def self.search(search_for)
    Picture.where("name = ?", search_for)
  
  validates_presence_of :name
end
 
 mount_uploader :image, ImageUploader

   
  end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
    
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
    @order_item = current_order.order_items.new
    
    if params[:search]
    @pictures = @pictures.search(params[:search])
    @pictures = @pictures#.order("created_at ASC") 
    else
    @pictures = @pictures#.order("created_at DESC")
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:name, :width, :height, :price, :artist, :desc, :image)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for @picture do |f| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :width %>
    <%= f.number_field :width %>
  </div>

  <div class="field">
    <%= f.label :height %>
    <%= f.number_field :height %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </div>

  <div class="field">
    <%= f.label :desc %>
    <%= f.text_area :desc %>
  </div>
  
  <div class="field">
    add an image....
    <%= f.file_field :image %>
  </div>
  
   <div class="actions">
    <%= f.submit %>
  </div>
  
 <% end %>

app/views/pictures/_picture_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= picture.name %></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
      
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency picture.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :picture_id, value: picture.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag(pictures_path, :method => "get") do %>
<%= text_field_tag :search, nil, :placeholder => "Search Pictures by Name" %>
<%= submit_tag "search" %>
<% end %>

<div>
  <div>
     <% #@pictures.each do |picture| %>
      <%#= render "picture_row", pictures: picture, order_items: @order_item %>
    <%# end %>
  </div>
</div>

<h1>Pictures</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Width</th>
      <th>Height</th>
      <th>Price</th>
      <th>Artist</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.name %></td>
        <td><%= picture.width %></td>
        <td><%= picture.height %></td>
        <td><%= picture.price %></td>
        <td><%= picture.artist %></td>
        <td><%= picture.desc %></td>
        <td><%#= image_tag(@picture.image_url.to_s) %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>   
  </tbody>
</table>

<br>


<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @picture.name %>
</p>

<p>
  <strong>Width:</strong>
  <%= @picture.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @picture.height %>
</p>

<p>
  <strong>Price:</strong>
  <%= @picture.price %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @picture.artist %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @picture.desc %>
</p>

<div>
<strong>Image</strong>
<%= image_tag(@picture.image_url(:thumb).to_s) %>
</div>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>